Repository cse110-fa22-group29/cse110-fa22-group29, pull requests merged in 2022-11, with the labels that each got.

#31 Implement simple CI pipeline
  .github/workflows/deploy-githubpages.yml
Labels: enhancement

#38 Implement JS unit test framework and CI pipeline actions
  .github/workflows/deploy-githubpages.yml
  .github/workflows/js-unittest.yml
  .gitignore
  package.json
  testenv/testenv.js
  testenv/testenv.test.js
  testenv/testenv_helpers.js
Labels: enhancement, CI

#44 Fix scripts in package.json for correct recursive calling
  package.json
Labels: bug, CI, Arthur, Unit Test

#47 Fix JS unit test ES6 compatibility
  .github/workflows/js-unittest.yml
  package.json
  source/assets/scripts/localStorage.js
  source/assets/scripts/localStorage.test.js
  source/assets/scripts/testenv.js
  testenv/testenv.js
  testenv/testenv.test.js
  testenv/testenv_helpers.js
Labels: bug, CI, Arthur

#62 Implement End to End Testing Framework
  .github/workflows/js-unittest.yml
  package.json
  source/assets/scripts/localStorage.test.js
  source/assets/scripts/main.e2e.test.js
  specs/adrs/111622-e2etesting-puppeteer.md
Labels: enhancement, CI, Unit Test

#68 Add link to app in README.md
  README.md
Labels: documentation

#69 Remove unused files
  source/assets/images/1_spooky-ghost-cookies.jpeg
  source/assets/images/2_frightfully-easy-ghost-cookies.jpeg
  source/assets/images/3_ingredient-ghost-halloween-cookies.jpeg
  source/reviews.json
Labels: enhancement

#75 implementation of basic image local storage
  source/CreatePage.html
  source/ReviewDetails.html
  source/assets/scripts/CreatePage.js
  source/assets/scripts/ReviewDetails.js
  source/index.html
Labels: Backend

#99 Add prettier
  .github/workflows/prettier.yml
  package.json
  specs/adrs/112922-prettier.md
Labels: enhancement, CI
